name: Eingabe Ausgabe
markdown: kramdown
highlighter: true
baseurl: /eingabe-ausgabe
mail: moron-zirfas@fh-potsdam.de 
exclude: 
  - .htaccess
  - bin
  - blog
  - bits
  - bower_components
  - crowdsourcing
  - node_modules
  - algorithms
  - MIT-License.txt
  - package.json
  - bower.json
  - config.codekit
  - Gruntfile.js
  - eingabe-ausgabe.sublime-project
  - eingabe-ausgabe.sublime-workspace
  - README.md
  - .codekit-cache
  - stylus
  - generate.sh
  - build.sh
sass:
  sass_dir: _sass
  style: :compressed
permalink: /blog/:categories/:year/:month/:day/:title.html
